{% set name = "xpublish-opendap" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xpublish_opendap-{{ version }}.tar.gz
  sha256: 957730dbe8e8c6d906aefd414a43d4325baf927063ecbb1d0ec6a8f3d8cbebdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - opendap-protocol <1.2.0
    - xarray
    - xpublish <0.4.0,>=0.3.0

test:
  imports:
    - xpublish_opendap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xpublish-community/xpublish-opendap/
  summary: OpenDAP endpoint plugin for Xpublish
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abkfenris
